{% set version = "3.0.1" %}

package:
  name: hicstuff
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hicstuff/hicstuff-{{ version }}.tar.gz
  sha256: 6294c30ddf5f5f4d46cca62cc7ba24ab939048c1c3ed17734971b62d87b6bc74

build:
  number: 0
  noarch: python
  entry_points:
    - hicstuff=hicstuff.main:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6,<3.8
    - pip
  run:
    - python >=3.6,<3.8
    - biopython
    - docopt
    - matplotlib-base
    - numpy
    - pandas
    - pysam
    - requests
    - scipy
    - scikit-learn
    - minimap2 
    - bowtie2 
    - samtools

test:
  imports:
    - hicstuff
  commands:
    - hicstuff --help

about:
  home: https://github.com/koszullab/hicstuff
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: "General purpose stuff to generate and handle Hi-C data in its simplest form."
  doc_url: https://hicstuff.readthedocs.io/en/latest/
  dev_url: https://github.com/koszullab/hicstuff

extra:
  recipe-maintainers:
    - lecorguille
