package:
  name: oligoarrayaux
  version: 3.8

source:
  url: http://unafold.rna.albany.edu/cgi-bin/OligoArrayAux-download.cgi?oligoarrayaux-3.8.tar.gz
  sha256: 43f5ca8beebad176b1e4883bffd9a16ede5f43b5aadd8abab3616fc58e761404

build:
  number: 1
    
requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - gawk
    - grep
    - perl >=5.6.1

test:
  commands:
    - hybrid-min -h 2>&1 | grep Usage

about:
  home: http://unafold.rna.albany.edu/?q=DINAMelt/OligoArrayAux
  license: ACADEMIC NON-COMMERCIAL USE LICENSE
  license_file: LICENSE
  summary: OligoArrayAux is a subset of the UNAFold package for use with OligoArray.

extra:
  identifiers:
    - doi:10.1007/978-1-60327-429-6_1
