{% set version = "1.0" %}

package:
  name: deepsig
  version: '{{ version }}'

source:
  url: https://github.com/BolognaBiocomp/deepsig/archive/v{{ version }}.tar.gz
  sha256: ''

build:
  noarch: python
  number: 0
  entry_points:
    - deepsig = deepsig.deepsig:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - biopython >=1.78

test:
  import:
    - Bio.SeqIO
  commands:
    - deepsig --help

about:
  home: https://github.com/BolognaBiocomp/deepsig
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Predictor of signal peptides in proteins based on deep learning
  dev_url: https://github.com/BolognaBiocomp/deepsig

extra:
  recipe-maintainers:
    - Castrense Savojardo
