{% set version="0.1" %}

build:
  skip: True  # [py>=30]
  number: 4

package:
  name: fargene
  version: {{ version }}

source:
  - url: https://github.com/thanhleviet/fargene/archive/v{{ version }}.tar.gz
    sha256: a5e05e6664ea4fb22b34ea4115ccd17efe396cfeb43b8fe2cb2a45e4c5652c27
  - url: ftp://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/ORFfinder/linux-i64/ORFfinder.gz  # [linux]
    sha256: bb676b56f557128e73f68cc852709d1ff7abd1c750d00fd8322de31820969f3c        # [linux]


requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - biopython >=1.68
    - PyYAML
    - numpy
    - matplotlib
    - emboss
    - seqtk
    - hmmer
    - trim-galore
    - clustalo
    - spades
    - prodigal

test:
  commands:
    - fargene --help
    - command -v ORFfinder  # [linux]

about:
  home: https://github.com/fannyhb/fargene
  license: 'MIT'
  license_file: LICENSE.md
  summary: 'Fragmented Antibiotic Resistance Gene iENntifiEr takes either fragmented metagenomic data or longer sequences as input and predicts and delivers full-length antiobiotic resistance genes as output'

extra:
  recipe-maintainers:
    - thanhleviet
