{% set version = "1.14.0" %}

package:
  name: nanocomp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nanocomp/NanoComp-{{ version }}.tar.gz
  sha256: ca2b214d68b8f8d65d9516f51bfc801e768e2984c3e87effff37a51777222ed9

build:
  entry_points:
    - NanoComp=nanocomp.NanoComp:main
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3
    - setuptools
  run:
    - python >=3
    - pandas
    - nanoget >=1.4.0
    - nanomath >=1.0.0
    - NanoPlot >=1.21.0
    - psutil
    - plotly >=3.4.2
    - seaborn>=0.9.0
    - matplotlib-base >=2.1.0
    - joypy
    - pyarrow

test:
  imports:
    - nanocomp

  commands:
    - NanoComp --help

about:
  home: https://github.com/wdecoster/NanoComp
  license: GPL-3.0-only
  summary: 'Comparing runs of Oxford Nanopore sequencing data and alignments'
  license_family: GPL
