{% set version = "0.1.1" %}
{% set github = "https://github.com/acidgenomics/acidgenomes" %}

package:
  name: r-acidgenomes
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 1928e51853aa6345a9335c9bc8646ef2c958de9cf0b28de5c3dec28ed28e53f4

build:
  number: 1
  noarch: generic

requirements:
  host:
    - r-base 
    - r-acidbase >=0.2.3
    - r-acidgenerics >=0.4.0
    - r-acidplyr >=0.1.2
    - bioconductor-annotationdbi
    - bioconductor-annotationhub
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-cli >=2.0
    - bioconductor-ensembldb
    - r-goalie >=0.4.9
    - r-pipette >=0.4.18
    - r-stringr >=1.4
    - r-syntactic >=0.4.3
      # Suggests
    - bioconductor-ensdb.hsapiens.v75
    - bioconductor-genomicfeatures
    - bioconductor-biomart
    - r-knitr
    - r-rmarkdown
  run:
    - r-base
    - r-acidbase >=0.2.3
    - r-acidgenerics >=0.4.0
    - r-acidplyr >=0.1.2
    - bioconductor-annotationdbi
    - bioconductor-annotationhub
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-cli >=2.0
    - bioconductor-ensembldb
    - r-goalie >=0.4.9
    - r-pipette >=0.4.18
    - r-stringr >=1.4
    - r-syntactic >=0.4.3
      # Suggests
    - bioconductor-ensdb.hsapiens.v75
    - bioconductor-genomicfeatures
    - bioconductor-biomart
    - r-knitr
    - r-rmarkdown

test:
  commands:
    - $R -e "library('AcidGenomes')"

about:
  home: https://acidgenomes.acidgenomics.com/
  dev_url: "{{ github }}"
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Toolkit for downloading and processing genome annotations.

extra:
  recipe-maintainers:
    - mjsteinbaugh
