{% set version = "0.1.4" %}
{% set github = "https://github.com/acidgenomics/acidplyr" %}

package:
  name: r-acidplyr
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 159d55dc4b0834c7c11a5c1cfa91f38530a93189fceefec8368af1dc80c2f42f
  
build:
  number: 1
  noarch: generic

requirements:
  host:
    - r-base
    - r-acidbase >=0.2.3
    - r-acidgenerics >=0.4.0
    - bioconductor-s4vectors
    - r-cli >=2.0
    - r-goalie >=0.4.9
    - r-tibble >=3.0
  run:
    - r-base
    - r-acidbase >=0.2.3
    - r-acidgenerics >=0.4.0
    - bioconductor-s4vectors
    - r-cli >=2.0
    - r-goalie >=0.4.9
    - r-tibble >=3.0

test:
  commands:
    - $R -e "library('AcidPlyr')"

about:
  home: https://acidplyr.acidgenomics.com/
  dev_url: "{{ github }}"
  license: MIT
  license_file: LICENSE
  summary: A dplyr-like approach for classes defined in S4Vectors.

extra:
  recipe-maintainers:
    - mjsteinbaugh
