{% set version = "0.2.6" %}
{% set github = "https://github.com/acidgenomics/AcidBase" %}

package:
  name: r-acidbase
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 62d91cb952f45dbb98c1677a3bccbecf8a43c79cba603fcfd0ee42de0dde55f6
  
build:
  number: 1
  noarch: generic

requirements:
  host:
    - r-base
    - r-acidgenerics >=0.4.1
  run:
    - r-base
    - r-acidgenerics >=0.4.1

test:
  commands:
    - $R -e "library('AcidBase')"

about:
  home: https://acidbase.acidgenomics.com/
  dev_url: "{{ github }}"
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Low-level base functions imported by Acid Genomics packages.

extra:
  recipe-maintainers:
    - mjsteinbaugh
