package:
  name: "isoplot"
  version: "1.1.1"

source:
  url: https://files.pythonhosted.org/packages/b7/9f/7f83e24a236b3e3abec8c4ce1efd9af9a3843a915230d78d10c8b32848e1/isoplot-1.1.1.tar.gz
  sha256: 9b0022130eff2686217d382c4a35e25068e1057af53ca679f264c5bbc33da0ff

build:
  number: 0
  noarch: python
  entry_points:
    - isoplot = isoplot.isoplotcli:initialize_cli
  script: python -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - bokeh ==2.0.2
    - colorcet >=2.0.2
    - ipywidgets >=7.5.1
    - matplotlib-base >=3.3.1
    - natsort >=7.0.1
    - numpy >=1.19.1
    - openpyxl >=3.0.5
    - pandas >=1.1.1
    - python
    - seaborn >=0.10.1
    - xlrd >=1.2.0

test:
  imports:
    - isoplot
  commands:
    - pip check
    - isoplot --help
  requires:
    - pip

about:
  home: https://github.com/LoloPopoPy/Isoplot
  summary: Generate figures from Isocor output
  license_file: LICENSE.txt
  license: GNU General Public v3 or later (GPLv3+)
  license_family: GPL3
  doc_url: https://isoplot.readthedocs.io/
  dev_url: https://github.com/LoloPopoPy/Isoplot

extra:
  recipe-maintainers:
    - LoloPopoPy
